---
- name: Set up Linkwarden
  hosts: portainer
  vars:
    project_dir: "/srv/linkwarden"
    proxy_conf_dir: "/srv/web"
    project_url: "linkwarden.ts.millim.no"
  tasks:
    - name: Ensure project directory exists
      ansible.builtin.file:
        path: "{{ project_dir }}"
        state: directory
        mode: "0775"
    # - name: Ensure data directory exists
    #   ansible.builtin.file:
    #     path: "{{ project_dir }}/data"
    #     state: directory
    #     mode: "0775"
    - name: Ensure correct dotenv file exists
      ansible.builtin.template:
        src: linkwarden/linkwarden.env.j2
        dest: "{{ project_dir }}/.env"
        mode: "0664"
    - name: Ensure Compose project exists
      ansible.builtin.template:
        src: linkwarden/linkwarden-compose.yml.j2
        dest: "{{ project_dir }}/compose.yml"
        mode: "0664"
    - name: Run the Compose project
      community.docker.docker_compose_v2:
        project_src: "{{ project_dir }}"
    - name: Deploy reverse proxy configuration
      ansible.builtin.template:
        src: linkwarden/linkwarden-reverse-proxy.conf.j2
        dest: "{{ proxy_conf_dir }}/linkwarden.conf"
        mode: "0664"
      register: proxyconf
    - name: Reload server configuration
      community.docker.docker_container_exec:
        container: web
        command: killall -HUP httpd
      when: "{{ proxyconf.changed }}"
- name: Public Linkwarden ingress
  hosts: millim.no
  vars:
    project_url: "linkwarden.ts.millim.no"
    public_url: "linkwarden.millim.no"
    proxy_conf_dir: "/srv/web/homelab"
  tasks:
    - name: Deploy reverse proxy configuration
      ansible.builtin.template:
        src: linkwarden/public.conf.j2
        dest: "{{ proxy_conf_dir }}/linkwarden.conf"
        mode: "0664"
      register: proxyconf
    - name: Reload server configuration
      community.docker.docker_container_exec:
        container: web-2
        command: killall -HUP httpd
      when: "{{ proxyconf.changed }}"
